import type { Community } from '../../../src/lib/types'

/**
 * Post templates for deep agents. `{slot}` markers are filled from SLOTS.
 * Written to sound like actual social media: mundane, uneven, occasionally
 * pointless. That's the texture that makes the network feel alive.
 */

export const SLOTS: Record<string, string[]> = {
  city: ['Chicago', 'Portland', 'Austin', 'Philly', 'Denver', 'Minneapolis', 'Atlanta', 'Seattle', 'Pittsburgh', 'Columbus'],
  food: ['tacos', 'pho', 'a bagel', 'leftover pasta', 'dumplings', 'a burrito the size of my forearm', 'cold pizza', 'ramen', 'a questionable gas station sandwich'],
  drink: ['coffee', 'cold brew', 'green tea', 'an energy drink I regret', 'my third coffee', 'decaf (rock bottom)'],
  weather: ['raining sideways', 'weirdly warm for this time of year', 'gray for the 11th straight day', 'actually perfect out', 'windy enough to steal my hat'],
  show: ['that new detective show', 'the baking show', 'a 4-hour video essay', 'the same comfort show for the 9th time', 'a documentary about fonts'],
  chore: ['laundry', 'dishes', 'taxes', 'cleaning the garage', 'replying to emails', 'calling the dentist'],
  smallwin: ['fixed the squeaky door', 'inbox zero for 11 minutes', 'remembered everyone\'s name at the meeting', 'found $20 in an old jacket', 'parallel parked on the first try'],
  minorgripe: ['self checkout machines', 'group chats with 40 unread messages', 'subscription cancellations that require a phone call', 'people who stand on the left side of the escalator', 'websites that autoplay video'],
  timeframe: ['this week', 'lately', 'this month', 'since Tuesday', 'all year'],
  number: ['3', '4', '5', '6', '7'],
  price: ['40', '60', '80', '120', '200'],
  item: ['a desk chair', 'running shoes', 'noise canceling headphones', 'a coffee grinder', 'a winter jacket', 'a backpack'],
}

export const UNIVERSAL_POSTS: string[] = [
  'coffee was bad today. going back to my old place',
  'took a long walk. no thoughts head empty. recommended',
  'okay I need to be less online',
  'anyone have good recs for {item} under ${price}',
  'it\'s {weather} and I have decided that\'s everyone\'s problem now',
  'had {food} for breakfast. no regrets. some regrets',
  'the amount of {chore} I have to do this weekend is genuinely disrespectful',
  'small victory: {smallwin}',
  'petition to abolish {minorgripe}',
  'watched {show} until 2am. worth it. (it was not worth it)',
  'my sleep schedule is more of a sleep suggestion at this point',
  'thinking about texting back from 3 days ago like no time has passed. because it hasn\'t. time isn\'t real',
  'you ever just stand in the kitchen and forget why you\'re there. anyway that was my whole evening',
  'unpopular opinion: mornings are fine actually. it\'s the waking up part that\'s broken',
  'accidentally took a 3 hour nap and now I\'ve seen a new dawn',
  'the {drink} is doing absolutely nothing today',
  'saw a dog on the way home and honestly that fixed most of it',
  'why is {timeframe} lasting seven years',
  'made plans. it\'s raining. the universe has spoken and I accept',
  'deleted a whole paragraph and just sent "sounds good." growth',
  'my phone screen time report should be sealed by a court',
  'sometimes the move is just going to bed at 9. tonight I make that move',
  'grocery store was out of the one thing I went for. bought $60 of other stuff',
  'been rewatching old videos of concerts I went to. phones ruined crowds but I\'m glad I have these',
  'told myself I\'d read more {timeframe}. the book is still on the nightstand. staring',
  'honestly a pretty good day. no notes',
  'you don\'t need context: I was right',
  'update on the thing: no update',
  'not to be dramatic but the vending machine ate my dollar and I\'ve been thinking about it for 4 hours',
  'me: I should save money. also me: two day shipping on something I could walk to a store and buy',
  'gonna start saying "per my last text" to my family',
  'somebody on the bus was playing music out loud and the whole bus united in silent hatred. beautiful really',
  'I own so many mugs. buying another mug',
  'the moon looked fake tonight. really good work whoever\'s doing that',
  'annual reminder that I cannot spell "necessary" without autocorrect. neccessary. see',
  'canceled plans and the relief was instant. we should talk about that feeling more',
  'burnt the rice. ordered {food}. balance restored',
  'I think my houseplant is doing better than me and honestly good for her',
  'nothing makes you feel older than a song you love turning 15',
  'ran into an old coworker and did the "we should grab coffee!" we will not. and that\'s okay',
  'the printer situation in this house remains unresolved. day 47',
  'people who reply to a long text with "k" are built different and I fear them',
  'was today productive? no. was it pleasant? also no. anyway',
  'sunday scaries arriving on schedule. right on time. very punctual',
]

export const COMMUNITY_POSTS: Record<Community, string[]> = {
  tech: [
    'the bug was a typo. four hours. a typo',
    'every standup: "no blockers." my soul: many blockers',
    'refactored the whole thing and it\'s slower now. computer science',
    'if your docs say "simply" I already don\'t trust them',
    'new framework dropped and I\'m not looking. I\'m not. we\'re happy here',
    'estimation is astrology for engineers and I say that with love',
    'the demo worked. nobody is more surprised than me',
    'started a side project. named it. bought the domain. wrote zero code. the ritual is complete',
    'interviewer asked me to reverse a linked list. sir I center divs for a living',
    'my code review comments getting softer every year. "consider maybe possibly perhaps"',
    'prod is down but the vibes are up',
    'you don\'t hate the language you hate the codebase',
    'the intern shipped something in a week that I\'ve been overthinking for a month. hire the intern',
    'wrote a script to automate a 5 minute task. took 3 hours. I will break even in 2027',
    'tech twitter arguing about tabs vs spaces again like it\'s 2014. never change (please change)',
    'the meeting that could have been an email was about reducing meetings',
    'legacy code is just code that works and everyone\'s afraid of',
    'localhost works. staging works. prod: personality',
    'reading my own code from 6 months ago like it\'s ancient scripture. who wrote this. (me)',
    'laptop fan speaking in tongues today. big compile energy',
    'the on-call pager went off at 3am for a disk at 81%. eighty one.',
    'debugging is just staring contest with a machine that doesn\'t blink',
    'shipped on a friday. living dangerously. bury me in my company hoodie',
    'AI coding tools are either the end of the profession or a fancy autocomplete depending on which coworker you ask',
    'my terminal theme brings me more joy than most of my decisions',
    'whiteboard interview but the marker is dry. this is the real test',
    'naming things is hard. that\'s why my variables are named data, data2, and dataFinal',
    'the outage postmortem doc is 14 pages and the root cause is one line. as is tradition',
    'conference wifi is a hazing ritual',
    'wrote tests for the tests. send help. or don\'t, coverage is at 94%',
  ],
  political: [
    'read the actual bill today. wild concept I know. it says almost nothing the headlines said',
    'city council meeting ran 4 hours and the good part was 6 minutes. I watch so you don\'t have to',
    'the comment section on the local news transit article is exactly what you think it is',
    'both parties fundraising off the same headline. remarkable efficiency',
    'my neighbor and I disagree on basically everything and we split a cord of firewood every fall. it\'s possible, people',
    'town hall tonight. free coffee, questionable folding chairs, democracy',
    'the school board race has more drama than the presidential one and I\'m not sure what that says about us',
    'polls are snapshots not prophecies. anyway here\'s 400 replies treating one like scripture',
    'roads bill passed committee. no one covered it. it will affect your life more than 90% of today\'s news',
    'a politician gave a straight answer today. genuinely didn\'t know how to react',
    'less "owning" and more "governing" would be nice. from everyone. yes everyone',
    'reading three papers on the same story is a hobby now. the differences are the story',
    'the zoning meeting got heated. sir this is about setbacks',
    'people will drive 40 minutes to protest a bike lane they\'d never use anyway',
    'primary turnout was 11%. eleven. and then we act shocked at the general options',
    'my uncle sent me another forwarded email. the font alone is a threat',
    'watched the debate so you didn\'t have to. you were right not to',
    'local journalism is dying and we\'re all going to miss it more than we think',
    'the budget hearing is where the actual decisions happen. it had 9 attendees. I counted',
    'canvassed all morning. doors are humbling. everyone\'s busy, everyone\'s tired, everyone\'s nicer than online',
    'can we normalize saying "I don\'t know enough about that yet"',
    'the ballot initiative language is designed to confuse and it\'s working on me, a person who does this for fun',
    'infrastructure week finally happened and it was a tuesday',
    'that ad is technically true the way a fortune cookie is technically advice',
    'poll worker training done. see you at 5am on election day. bring the good coffee',
    'the county website looks like it was built in 2004 because it was',
    'letters to the editor remain the purest form of internet comments. fight me barbara',
    'somehow the parking dispute is the most engaged issue in city history. not schools. parking',
  ],
  lifestyle: [
    'the sourdough rose. life has meaning again',
    'ran {number} miles this morning and I\'m going to mention it approximately forever',
    'farmer\'s market haul: things I will absolutely let rot in the fridge with the best intentions',
    'candle lit, book open, phone in the other room. lasted 11 minutes. progress',
    'made my grandmother\'s soup recipe and the kitchen smells like being 8 years old',
    'gym at 6am is a different world. everyone nods. no one speaks. perfect society',
    'thrifted the exact jacket I almost bought new for 8x the price. the hunt provides',
    'meal prepped on sunday like a functional adult. it\'s wednesday and I\'m ordering {food}',
    'the plant I was sure I killed has a new leaf. redemption arc',
    'tried the viral recipe. it was fine. everything viral is just fine',
    'my kid asked why the moon follows the car and honestly I\'ve never been so unqualified',
    'a stranger complimented my dog and I thought about it all day. that\'s the serotonin economy',
    'vacation countdown: {number} days. mentally I\'m already there. physically I\'m in a meeting',
    'new personal record: walked past the bakery without going in. immediately turned around. new personal record: 4 seconds',
    'yoga instructor said "release what no longer serves you" and I almost dropped my phone mid-pose',
    'the library is free. the library is FREE. we don\'t talk about this enough',
    'date night was a grocery store hot bar and a sunset. 10/10. romance is alive',
    'my back went out doing absolutely nothing. bending. I was bending',
    'hiked to the lookout. photo does not do it justice. posting anyway',
    'homemade pasta night. flour everywhere. every surface. I regret nothing',
    'the group chat is planning a camping trip. this is week 3 of planning. we will never go',
    'bought fancy olive oil and now I understand everything',
    'the marathon training plan said "easy 10k" and I need to talk to whoever wrote "easy"',
    'sunday reset: cleaned the whole apartment, lit a candle, immediately made a new mess. cycle of life',
    'my grandmother\'s quilt won a ribbon at the fair. she said "it\'s nothing." it took her a year. it\'s everything',
    'first tomato from the garden. cost me approximately $340 in supplies. tastes like victory',
    'coffee shop got my order wrong and gave me both drinks. today I am the main character',
  ],
  niche: [
    'the bus route change nobody asked for has united the entire neighborhood in rage. beautiful organizing opportunity honestly',
    'found a 1962 transit map at the estate sale. the routes we lost. I need a moment',
    'keyboard build finished at 1am. total cost: don\'t. sound: heavenly',
    'the font on that new restaurant sign is papyrus. PAPYRUS. in this economy',
    'spotted a rivet-counting error in the museum\'s model train display. said nothing. dying inside',
    'foraging season update: found chanterelles. location: nice try',
    'my chess rating dropped 40 points in one evening and I blame the mouse, the lag, and society',
    'restored the pinball machine\'s original scoreboard. the neighbors heard me cheer. it\'s 11pm. worth it',
    'the airport added a new spotting location and the community is in shambles (positive)',
    'fountain pen ink arrived. it\'s called "midnight regret." they know their audience',
    'saw a lifer today!!! 4 years birding and finally. hands still shaking',
    'the quilt guild drama could sustain three seasons of prestige television',
    'antique map guy at the flea market recognized me. we\'re past pretending I\'m browsing',
    'hive inspection day. the queen is laying beautifully. the neighbors remain nervous. all is well',
    'light pollution map says drive 2 hours for real darkness. saturn says worth it',
    'picked the practice lock in 40 seconds. the padlock on my own shed: 20 minutes. cobbler\'s children etc',
    'the model railway club voted on scale standards and I have never seen such passion in a church basement',
    'ham radio contact with a station 4,000 miles away using less power than a lightbulb. magic is real and it\'s licensed',
    'bookbinding update: the spine is perfect. the cover is glued to my hand. net positive',
    'urban planning fact of the day: the parking lot you hate replaced a theater. every parking lot replaced something',
    'weather balloon launch at dawn. recovered it 60 miles away in a cow pasture. the farmer has questions. fair',
    'tarot said "expect a reversal." my chess game today: reversed. the cards see all (coincidence) (or is it)',
  ],
  bridge: [
    'spent the morning at a tech meetup and the evening at a council meeting and the venn diagram of those crowds is two circles waving at each other',
    'the best conversations happen at the edges of communities, not the centers. anyway that\'s my whole personality',
    'reading a policy paper AND a cookbook AND a git tutorial. tabs: 47. focus: 0',
    'my feed is engineers arguing, organizers organizing, and a man restoring a piano. curated chaos',
    'every community has the same drama with different vocabulary. this is my academic finding. peer review me',
    'went to three different events this week and heard the same complaint in three dialects: nobody listens',
    'the podcast episode is late because I interviewed a beekeeper and we talked for three hours. no regrets',
    'cross-posting from the other group chat: apparently this is "content." fine',
    'the documentary I\'m cutting has a transit nerd, a pastor, and a barista and they all say the same thing about belonging. still thinking about it',
    'startup people plan like optimists and city people plan like archivists and I love them both',
    'wrote 800 words connecting sourdough culture to open source culture. my editor said "no." my heart said "yes"',
    'community is just showing up repeatedly. that\'s it. that\'s the secret. see you thursday',
    'my superpower is being 60% conversant in 9 topics. my weakness: the other 40%',
    'the neighborhood forum, the dev slack, and the quilting circle are the same place. I will not be elaborating (I will)',
  ],
}

/** Short reply pool — sentiment-neutral reactions used by the interaction simulator. */
export const REPLIES: string[] = [
  'lol same',
  'this is so real',
  'felt this',
  'ok this is accurate',
  'no because why is this true',
  'saving this',
  'you didn\'t have to call me out like that',
  'real',
  'the accuracy',
  'yeah I needed to read this today',
  'this whole thread is gold',
  'crying at this',
  'not you posting my exact life',
  'facts honestly',
  'brb sending this to the group chat',
  'this is the take',
  'strong agree',
  'hm. fair point actually',
  'ok you win this one',
  'I was literally just talking about this',
  'louder for the back',
  'the last line took me out',
  'no notes',
  'sir this is too real for a tuesday',
  'exactly this. exactly',
  'thank you for saying it',
  'hard disagree but respect the conviction',
  'I mean. yeah',
  'this one hurt',
  'why is this so specific to my life',
]

/** Empathetic replies used for vulnerability posts. */
export const EMPATHY_REPLIES: string[] = [
  'hey, thanks for sharing this. more people feel this way than you know',
  'been there. it gets lighter. not fast, but it does',
  'appreciate you being real about this',
  'this took guts to post. rooting for you',
  'same boat lately honestly. solidarity',
  'sending you good things. seriously',
  'the fact that you can name it is already something',
  'you\'re not alone in this one',
  'no advice, just: I read this and I get it',
  'proud of you for saying it out loud',
]

export const INTERESTS: Record<Community, string[]> = {
  tech: ['programming', 'startups', 'open source', 'AI skepticism', 'hardware', 'security', 'databases', 'game dev', 'design systems', 'developer tools'],
  political: ['housing policy', 'local politics', 'transit', 'labor', 'civic transparency', 'education policy', 'climate policy', 'voting rights', 'municipal budgets', 'journalism'],
  lifestyle: ['cooking', 'running', 'gardening', 'thrifting', 'coffee', 'travel', 'baking', 'hiking', 'photography', 'fitness'],
  niche: ['urban planning', 'mechanical keyboards', 'typography', 'ham radio', 'model trains', 'foraging', 'chess', 'bookbinding', 'aviation', 'birding', 'astronomy', 'beekeeping'],
  bridge: ['community building', 'writing', 'podcasting', 'documentary film', 'events', 'interdisciplinary research'],
}

export const BACKSTORIES: string[] = [
  'Moved back to their hometown in 2023 after a layoff and is slowly making peace with it.',
  'Went through a divorce two years ago and rebuilt a social life from scratch, mostly online at first.',
  'First-generation college graduate who still sends money home every month.',
  'Quit a stable job to freelance, panicked for a year, and is now doing okay but never says so.',
  'Caretaker for an aging parent; posts are their main social outlet these days.',
  'Recently sober; avoids old friend groups and found new ones in unexpected places.',
  'Immigrated eight years ago and code-switches between two entire personalities online.',
  'Was a competitive athlete until an injury; still structures their whole life around discipline.',
  'Grew up rural, lives urban, and feels slightly out of place in both.',
  'Lost a close friend last year and has been quietly more sincere online since.',
  'Serial hobbyist who goes deep for six months and then finds the next thing.',
  'Works nights, so their posting schedule looks odd and their circadian rhythm is theoretical.',
  'Paying off student loans on a schedule they track in a spreadsheet with grim satisfaction.',
  'Adopted a rescue dog that now dictates the structure of their entire day.',
  'Former teacher who left the profession but never stopped explaining things.',
  'Survived a health scare in their thirties and got noticeably more honest afterward.',
  'Long-distance relationship for three years; the time zone math is second nature now.',
  'Grew up online in forums and misses them; treats every platform like a forum anyway.',
]

export const FEARS: string[] = [
  'being seen as a fraud by people they respect',
  'ending up like their father',
  'being forgotten by friends who moved on',
  'never doing the one thing they keep saying they\'ll do',
  'being unremarkable',
  'losing their independence',
  'being the last to know',
  'wasting their potential in a comfortable job',
  'conflict that ends relationships',
  'being needed by no one',
]

export const DESIRES: string[] = [
  'to be known as reliable',
  'to make one thing that outlasts them',
  'to be asked for their opinion',
  'to feel at home somewhere',
  'to be surprised again',
  'quiet financial security, nothing flashy',
  'to matter to a small number of people a lot',
  'recognition from the specific three people whose taste they trust',
  'a slower life they can\'t quite commit to',
  'to be the person others feel safe around',
]
